name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Typecheck, lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Install deps
        run: bun install --frozen-lockfile
      - name: Typecheck
        run: bun run typecheck
      - name: Lint
        run: bun run lint
      - name: Test
        run: bun run test
